#!/bin/bash

EXEC_DIR=$PWD
DIR=`dirname $PWD/$0`
INSTALL_DIR=`dirname $DIR`
INSTALL_DIR=`dirname $INSTALL_DIR`

chgrp -R www-data $INSTALL_DIR/data/
chmod -R 664 $INSTALL_DIR/data/
find $INSTALL_DIR/data/ -type d  -exec chmod 775 {} \;

mv $DIR/signetsim /etc/apache2/sites-available/

cd /etc/apache2/sites-enabled/
a2dissite *

a2enmod rewrite
a2enmod wsgi
a2ensite signetsim

cat /etc/apache2/sites-available/default
cat /etc/apache2/sites-available/signetsim

service apache2 reload
